# Generated by Django 4.2.10 on 2024-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='ip',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
