# Generated by Django 4.2.10 on 2024-04-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_names_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('created', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.names')),
            ],
        ),
    ]
